name: Label & comment issues and Greetings

on:
  issues:
    types:
      - reopened
      - opened
  pull_request:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue!
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment on first pull request
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.pull_request.number }}
          body: |
            Congratulations on opening your first pull request! 🎉
          github-token: ${{ secrets.GITHUB_TOKEN }}

  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed on users' first issue"
          pr-message: "Message that will be displayed on users' first pull request"
