name: Issue and PR automation

on:
  issues:
    types: [closed]
  pull_request:
    types: [opened]

jobs:
  issue_comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: Comment on closed issue
        uses: actions/github-script@v5
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The issue is now resolved.'
            })

  pr_comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Comment on first PR
        uses: actions/github-script@v5
        with:
          script: |
            let prs = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              creator: context.payload.pull_request.user.login
            })
            if (prs.data.length === 1) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Congratulations on opening your first pull request!'
              })
            }
